### ISSUE TITLE
Pop-up Menu CSS Logic Errors and Share menu CSS Logic Errors

### ISSUE THREAD

**Issue by coldenate** [catppuccin/remnote#12]
<details><summary><h2>Incorrect Color Design on a pop-up menu when hovering over power-up tag</h1></summary>

<img width="934" alt="image" src="https://user-images.githubusercontent.com/66754842/226496123-591fa1cb-55ca-46ee-a236-41618c83a617.png">

## Recreation

Take a rem that you can view in unzoomed view, tag it with `Disable Descendant Cards`, and hover over the identifier. ex.
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/66754842/226496403-3a94886c-bd7b-413b-852c-a3491c447d18.png">

</details>
<details><summary><h2>Incorrect Color Design viewing shared article</h1></summary>

## Recreation

Just share an article, and let Remnote take you to the self-share-view page. 

<img width="2440" alt="image" src="https://user-images.githubusercontent.com/66754842/226498354-7899cd63-1133-4d28-b18f-f1bf65aa39b7.png">
</details>

**Comment by coldenate** [comment]
I wrote this on a whim because I noticed it while studying. Please let me know if you would like more info. I plan to tackle this issue myself soon.

**Comment by justTOBBI** [comment]
I guess that got closed in the new PR?

**Comment by coldenate** [comment]
No mot yet. These were not fixed yet.
