### ISSUE TITLE
docs: Catwalk Image

### ISSUE THREAD

**Issue by justTOBBI** [catppuccin/remnote#15]
I just noticed the new Catwalk Image and well, that should be redone.
It should be in the Latte/Frappe/Macchiato/Mocha order :D

**Comment by justTOBBI** [comment]
I just noticed, that I can do it myself xd
Imma PR the change

**Comment by justTOBBI** [comment]
I updated the image, but it didnt seem to update?

**Comment by justTOBBI** [comment]
fixed with ca6e6ea

**Comment by coldenate** [comment]
Oh nice!! Thanks so much. I didn't even know there was a desired order. I was honestly bias for mocha and macchiato 😅
