### ISSUE TITLE
Clozes stand out too much

### ISSUE THREAD

**Issue by rayvin185** [catppuccin/remnote#19]
![image](https://github.com/catppuccin/remnote/assets/68744498/c4b57f70-55ae-470b-b8d1-b9a514c402d7)

### vs normal:
![image](https://github.com/catppuccin/remnote/assets/68744498/bdb096ea-ae01-4b8e-b7cc-78cca859345e)

It would be nice if they could blend in just a tiny bit more, similar to the normal look! Thanks so much for making this theme <3

**Comment by coldenate** [comment]
@rayvin185 Thanks for reporting! I will look into this!

**Comment by coldenate** [comment]
@rayvin185 In the meantime, the [`Minimal Clozes`](https://remnote.com/plugins/Anisha-MinimalClozes) plugin seems to alleviate many of the cloze issues. 
![image](https://github.com/catppuccin/remnote/assets/66754842/c94715d4-8229-4dd1-8967-7ff2453c4489)
![image](https://github.com/catppuccin/remnote/assets/66754842/e22ee9ba-fa6b-4ed6-9834-aa4e94dad0e9)

(mostly the dark themes seem to have better mileage for the **workaround**.)

**Comment by coldenate** [comment]
@rayvin185 I recently pushed a change to fix the cloze contrast. 
I’ll be marking this issue as closed for now. Feel free to reopen or give feedback on the update(v1.2.7).
