### ISSUE TITLE
Logseq like color schemes

### ISSUE THREAD

**Issue by SrSh-notme** [catppuccin/remnote#22]
Thank u for this great theme for remnote ！How about add logseq like chioce？

**Comment by griimick** [comment]
@SrSh-notme What do you mean by logseq like choices? If you mean accent color choices, you can customise under plugin settings.
<img width="709" alt="image" src="https://github.com/catppuccin/remnote/assets/10350864/de8c003d-d63f-4528-b93f-0bafa98bed7b">

**Comment by coldenate** [comment]
Loqseq is another app with its own color scheme. There is a plugin made for that use theme here: https://remnote.com/plugins/Firefly
You're also welcome to override the Catppuccin base colors with Loqseq colors, but you will have more mileage with the official plugin. :) 
Feel free to reopen if there's anything else you need.
