### ISSUE TITLE
Contrast Problem

### ISSUE THREAD

**Issue by SiamUddin12** [catppuccin/remnote#25]
There is a problem with the contrast of the theme. Almost every theme has contrast issues somewhere. Either it's hover or active. Sometimes it is not that good on the eyes. Besides, everything works just fine. It's an incredible theme. I hope the technical team will fix this in the shortest time possible and reserve it's top spot like always.

Regards.

**Comment by coldenate** [comment]
Hey! Thanks for stopping by and reporting this. Can you provide screenshots of the areas that are affected? This theme is derived from the Catppuccin palette, which was designed to have as few contrast issues as possible. That said, it’s likely my assignments of certain colors to certain components is what’s wrong here. So any example images would be immensely helpful!
