### ISSUE TITLE
corrupted images of themes on RemNote 

### ISSUE THREAD

**Issue by xnardoleo** [catppuccin/remnote#4]
Hey there! I've noticed all your themes on RemNote Theme Explorer are having a corrupted issue on the preview images, as shown bellow. Just thought it would be helpful to tell you that! 

My best regards!

![image](https://user-images.githubusercontent.com/15082872/217573781-8aacf1d1-b7c4-46f4-9cfa-ba3ced425421.png)

**Comment by justTOBBI** [comment]
Hey @xnardoleo this was already addressed in #2 and will be fixed after all these changes have been made. 
Thanks for pointing it out :D

**Comment by xnardoleo** [comment]
Great then! So let me take this opportunity to make a request for more light theme options 😄 haha
